version: '4.35'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8085:8085"
    restart: always
    environment:
      PORT: 8085
      MYSQL_HOST: database
      MYSQL_PORT: 3306
      MYSQL_DB: bite_booking
      MYSQL_USER: root
      MYSQL_PASSWORD: 
      DDL_AUTO: update
    depends_on:
      - database

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    restart: always

  database:
    image: mysql:8.0
    container_name: mysql-container
    ports:
      - "3308:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: bite_booking
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
